fixtures:
  repositories:
    registry:
      repo: 'git://github.com/puppetlabs/puppetlabs-registry.git'
      ref: '1.0.0'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '3.2.0'
    windows_firewall: 'git://github.com/rmsphd/puppet-windows_firewall.git'
  symlinks:
    rdp: "#{source_dir}"
