fixtures:
  repositories:
    registry:
      repo: 'git://github.com/puppetlabs/puppetlabs-registry.git'
      ref: '1.0.0'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '3.2.0'
    windows_firewall:
      repo: 'git://github.com/rmsphd/puppet-windows_firewall.git'
	  ref: 'ebd5ec316dcfc98a55737cdc880a9dba5eb84498'
  symlinks:
    rdp: "#{source_dir}"
